name: Docker Image builder

on:
  push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    container:
      image: docker:28.3.2-cli
    runs-on: [xx-small-k8s-mode]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: dremio-mcp-server:${{ github.sha }}
      - name: Validate docker
        run: |
          docker run -e TOOLS_MODE=FOR_DATA_PATTERNS \
              -e DREMIO_URI=https://fake \
              -e DREMIO_OAUTH_SUPPORTED=false \
          dremio-mcp-server:${{ github.sha }} \
            dremio-mcp-server tools list
      - name: Install uv
        run: |
           curl -LsSf https://astral.sh/uv/install.sh | sh
           echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Start container
        run: |
          docker run -e TOOLS_MODE=FOR_DATA_PATTERNS \
            -e DREMIO_URI=https://fake \
            -e DREMIO_OAUTH_SUPPORTED=false \
            -p 6789:6789 \
            --name mcp --rm \
            --network host \
          dremio-mcp-server:${{ github.sha }} \
          dremio-mcp-server run --enable-streaming-http --port 6789 --no-log-to-file \
            --enable-json-logging &

      - name: Test container
        run: |
          uv run python tests/stremable_http_cli.py --url http://127.0.0.1:6789/mcp --token fake

      - name: Stop container
        run: |
          docker stop mcp
          
